export const actionTypes = {
  AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS:",
  AUTH_USER_FAILED: "AUTH_USER_FAILED",

  START_LOADING: "START_LOADING",
  FINISH_LOADING: "FINISH_LOADING",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_FAILURE: "SIGN_UP_FAILED",

  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_FAILURE: "VERIFY_FAILURE",

  VERIFY_RE_SEND: "VERIFY_RE_SEND",
  RE_SEND_FAILURE: "RE_SEND_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILED",

  REFRESH_SESSION_SUCCES: "REFRESH_SESSION_SUCCES",
  REFRESH_SESSION_FAILED: "REFRESH_SESSION_FAILED",

  RECOVER_PASS_REQUEST: "RECOVER_PASS_REQUEST",
  RECOVER_PASS_REQUEST_FAILED: "RECOVER_PASS_REQUEST_FAILED",

  RECOVER_PASS_SUCCESS: "RECOVER_PASS_SUCCESS",
  RECOVER_PASS_FAILED: "RECOVER_PASS_FAILED",

  SIGN_OUT_SUCCES: "SIGN_OUT_SUCCES",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",
};

export const moviesTypes = {
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILURE: "GET_MOVIES_FAILURE",

  LIKE_MOVIE_SUCCESS: "LIKE_MOVIE_SUCCESS",
  LIKE_MOVIE_FAILURE: "LIKE_MOVIE_FAILURE",

  DISLIKE_MOVIE_SUCCESS: "DISLIKE_MOVIE_SUCCESS",
  DISLIKE_MOVIE_FAILURE: "DISLIKE_MOVIE_FAILURE",

  LIKED_MOVIES_SUCCESS: "LIKED_MOVIES_SUCCESS",
  LIKED_MOVIES_FAILURE: "LIKED_MOVIES_FAILURE",

  LIKED_MORE: "LIKED_MORE",
  LIKED_MORE_FAILED: "LIKED_MORE_FAILED",

  GET_NETWORKS_SUCCESS: "GET_NETWORKS_SUCCESS",
  GET_NETWORKS_FAILED: "GET_NETWORKS_FAILED",

  UPDATE_NETWORK_SUCCESS: "UPDATE_NETWORK_SUCCESS",
  UPDATE_NETWORK_FAILED: "UPDATE_NETWORK_FAILED",

  GET_GENRES: "GET_GENRES",
  GET_GENRES_FAILED: "GET_GENRES_FAILED",

  CHANGE_GENRES: "CHANGE_GENRES",
  CHANGE_GENRES_FAILED: "CHANGE_GENRES_FAILED",
  
  CURRENT_MOVIE: "CURRENT_MOVIE",
};
